name: RunTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - "127.0.0.1:53:53"                # only required for Pro (DNS)
          - "127.0.0.1:53:53/udp"            # only required for Pro (DNS)
          - "127.0.0.1:443:443"              # only required for Pro (LocalStack HTTPS Edge Proxy)
          - "127.0.0.1:4510-4559:4510-4559"  # external service port range
          - "127.0.0.1:4566:4566"            # LocalStack Edge Proxy\
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: |
      #     apt update && apt install git curl unzip build-essential -y

      # - name: Install node
      #   run: |
      #     curl -fsSL https://deb.nodesource.com/setup_15.x | bash
      #     apt-get install -y nodejs

      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '>=1.17.0'
      - run: go version

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: Run the tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: cd ./test && go test -v